### ISSUE TITLE
any update here?

### ISSUE THREAD

**Issue by skycsky** [moazshorbagy/BlackClover-Go-IA#6]
Gui directory is empty , any progress on this ?
best regards!

**Comment by moazshorbagy** [comment]
The latest version is in this branch:
https://github.com/moazshorbagy/BlackClover-Go-IA/tree/gui-integration

That's how the GUI looks:
![image](https://user-images.githubusercontent.com/37043684/79412357-91c29000-7fa5-11ea-9ab9-421d0c165e26.png)

**Comment by skycsky** [comment]
thanks a lots！
